"""Configuration package for the IPTC entity-enhanced pipeline.

Public API is re-exported here so existing imports keep working::

    from iptc_entity_pipeline.config import BaseCnf, get_config
"""

# Import order matters: base -> variants -> sources/language -> registry.
from iptc_entity_pipeline.config.base import (
    ALL_ENTITY_LANGS,
    DATA_ROOT,
    GOLD_ORIGIN_TEST_CSV,
    GOLD_ORIGIN_TRAIN_CSV,
    AssemblyCnf,
    AssemblyMemberCnf,
    BaseCnf,
    BaseCnfWithHPO,
    BaseCnfWithHPO2,
    CvCnf,
    EmbeddingCnf,
    EvaluationCnf,
    HyperparamSpace,
    ModelCnf,
    OptunaCnf,
    PathsCnf,
    PreBaseCnfWithHPO,
    ThresholdTuningCnf,
    TrainingCnf,
    conf_from_dict,
    resolve_paths,
)
from iptc_entity_pipeline.config.article_only import (
    ArticleOnlyCnf,
    ArticleOnlyGeluCnf,
    ArticleOnlyLeakyCnf,
    ArticleOnlyPriorCnf,
    ArticleOnlySkipCnf,
    ArticleOnlyTunedCnf,
    ArticleOnlyTunedDiffThresholdsCnf,
    BestArticleOnlyCnf,
    BestArticleOnlyTunedCnf,
)
from iptc_entity_pipeline.config.wpentities import (
    BestWpEntitiesAttentionCnf,
    BestWpEntitiesAttentionHPOCnf,
    BestWpEntitiesMhaAttention2Cnf,
    BestWpEntitiesMhaAttentionCnf,
    BestWpEntitiesTunedCnf,
    EntityOnlyCnf,
    WPEntitiesAttentionHPOCnf,
    WPEntitiesMeanCnf,
    WPEntitiesMeanNoLocationCnf,
    WPEntitiesMeanOnlyEventCnf,
    WPEntitiesMeanOnlyGeneralCnf,
    WPEntitiesMeanOnlyLocationCnf,
    WPEntitiesMeanOnlyOrganizationCnf,
    WPEntitiesMeanOnlyOtherCnf,
    WPEntitiesMeanOnlyPersonCnf,
    WPEntitiesMeanOnlyProductCnf,
    WPEntitiesMentionWeightedMeanCnf,
    WPEntitiesPmmAttentionHPOCnf,
    WPEntitiesRelevanceWeightedMeanCnf,
    WPEntitiesRelevanceWeightedSumCnf,
    WPEntityOnlyMeanCnf,
    WpEntitiesCnf,
    WpEntitiesGeluCnf,
    WpEntitiesLeakyCnf,
    WpEntitiesPmmMentionWeightedMeanCnf,
    WpEntitiesPmmTunedCnf,
    WpEntitiesPmmTunedOnlyCnf,
    WpEntitiesPmmTunedSumCnf,
    WpEntitiesPriorCnf,
    WpEntitiesSkipCnf,
    WpEntitiesTunedCnf,
)
from iptc_entity_pipeline.config.sources import (
    W2VecAttentionHPOCnf,
    W2VecMentionWeightedMeanCnf,
    W2VecRelevanceWeightedMeanCnf,
    WArticleAtentionCnf,
    WikiIntroAttentionHPOCnf,
    WikiIntroMentionWeightedMeanCnf,
    WikiIntroRelevanceWeightedMeanCnf,
    WikidataDescriptionAttentionCnf,
    WikidataDescriptionEntitiesCnf,
    WikidataDescriptionEntitiesMeanCnf,
    WikidataDescriptionEntitiesMeanJinaAllLangsFallbackCnf,
    WikidataDescriptionEntitiesMeanJinaCnf,
    WikidataDescriptionEntitiesSumCnf,
    WikidataDescriptionEntityOnlyCnf,
    WikidataDescriptionEntityOnlyMeanCnf,
    WikidataDescriptionMentionWeightedMeanCnf,
    Wikipedia2VecEntitiesCnf,
    Wikipedia2VecEntitiesMeanCnf,
    Wikipedia2VecEntityOnlyCnf,
    Wikipedia2VecEntityOnlyMeanCnf,
    WikipediaArticleEntitiesCnf,
    WikipediaArticleEntitiesMeanCnf,
    WikipediaArticleEntitiesSumCnf,
    WikipediaArticleEntityOnlyCnf,
    WikipediaArticleEntityOnlyMeanCnf,
    WikipediaArticleMentionWeightedMeanCnf,
    WikipediaIntroEntitiesCnf,
    WikipediaIntroEntitiesMeanCnf,
    WikipediaIntroEntitiesSumCnf,
    WikipediaIntroEntityOnlyCnf,
    WikipediaIntroEntityOnlyMeanCnf,
)
from iptc_entity_pipeline.config.language import (
    BWpEntitiesTunedAllLangsCnf,
    BWpEntitiesTunedAllLangsFallbackAttentionCnf,
    BWpEntitiesTunedAllLangsFallbackCnf,
    BWpEntitiesTunedCsCnf,
    BWpEntitiesTunedDeCnf,
    BWpEntitiesTunedEnCnf,
    BWpEntitiesTunedEnDeCnf,
    BWpEntitiesTunedEnDeFallbackCnf,
    BWpEntitiesTunedEnFallbackCnf,
    BWpEntitiesTunedEnNlCnf,
    BWpEntitiesTunedEnNlFallbackCnf,
    BWpEntitiesTunedEsCnf,
    BWpEntitiesTunedFrCnf,
    BWpEntitiesTunedNlCnf,
    BWpEntitiesTunedNlEnFallbackCnf,
)
from iptc_entity_pipeline.config.debug import (
    DebugAttention3Cnf,
    DebugAttentionCnf,
    DebugCnf,
    DebugEvalCnf,
    DebugMhaAttention2Cnf,
    DebugMhaAttentionCnf,
)
from iptc_entity_pipeline.config.registry import (
    PipelineCnf,
    get_config,
    list_config_names,
)

__all__ = [
    'ALL_ENTITY_LANGS',
    'DATA_ROOT',
    'GOLD_ORIGIN_TEST_CSV',
    'GOLD_ORIGIN_TRAIN_CSV',
    'AssemblyCnf',
    'AssemblyMemberCnf',
    'BaseCnf',
    'BaseCnfWithHPO',
    'BaseCnfWithHPO2',
    'CvCnf',
    'EmbeddingCnf',
    'EvaluationCnf',
    'HyperparamSpace',
    'ModelCnf',
    'OptunaCnf',
    'PathsCnf',
    'PipelineCnf',
    'PreBaseCnfWithHPO',
    'ThresholdTuningCnf',
    'TrainingCnf',
    'conf_from_dict',
    'get_config',
    'list_config_names',
    'resolve_paths',
]
